### ISSUE TITLE
Password Management 

### ISSUE THREAD

**Issue by danu3006** [mosaicnetworks/evm-lite-client#23]
Need accounts to be encrypted and decrypted with different passwords rather than a single password file. 

- Command `accounts create` should prompt for password by default unless or otherwise `-p, --passsword` flag is provided. [COMPLETED]
- Command `transfer` should also prompt for password by default when trying to transfer from an account.
- New command `accounts update <address>` should allow users to update password for an account if the previous password is known.

**Comment by arrivets** [comment]
`accounts list` does not need a pwd. Account info is public.
